import { useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { ArrowRight, Eye, EyeOff, LockKeyhole, Waves } from 'lucide-react';
import toast from 'react-hot-toast';
import { Button, Field } from '../../components/common/UI';
import { useAuth } from '../../context/AuthContext';
import { errorMessage } from '../../services/api';

function AuthShell({title,copy,children}){return <div className="auth-page"><aside className="auth-aside"><Link className="brand" to="/"><span className="brand-mark"><Waves/></span>CampusFlow</Link><div><span className="eyebrow">Campus time, returned</span><h1>One less line.<br/>A lot more day.</h1><p className="text-indigo-100 max-w-md">Live queues and appointments that keep campus services moving at a human pace.</p></div></aside><main className="auth-form-wrap"><div className="auth-form"><h2>{title}</h2><p>{copy}</p>{children}</div></main></div>}
export function Login(){const {user,login}=useAuth();const navigate=useNavigate();const [loading,setLoading]=useState(false);const [show,setShow]=useState(false);if(user)return <Navigate to={user.role==='admin'?'/admin':'/app'}/>;const submit=async(e)=>{e.preventDefault();setLoading(true);try{const logged=await login(Object.fromEntries(new FormData(e.currentTarget)));toast.success(`Welcome back, ${logged.name.split(' ')[0]}.`);navigate(logged.role==='admin'?'/admin':'/app')}catch(error){toast.error(errorMessage(error))}finally{setLoading(false)}};return <AuthShell title="Welcome back" copy="Sign in to manage your campus day."><form onSubmit={submit}><Field label="College email" name="email" type="email" required defaultValue="student@campusflow.demo"/><div className="password-wrap"><Field label="Password" name="password" type={show?'text':'password'} required defaultValue="Student@123"/><button className="password-toggle" type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><Button className="w-full mt-1" loading={loading}>Sign in <ArrowRight size={16}/></Button></form><div className="mt-5 p-4 bg-indigo-50 rounded-xl text-xs text-indigo-900"><b>Demo ready:</b> Student credentials are pre-filled. For admin, use admin@campusflow.demo / Admin@123.</div><p className="text-sm text-center mt-6">New to CampusFlow? <Link className="text-indigo-600 font-bold" to="/register">Create an account</Link></p></AuthShell>}
export function Register(){const {user,register}=useAuth();const navigate=useNavigate();const [loading,setLoading]=useState(false);const submit=async(e)=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));if(values.password!==values.confirmPassword)return toast.error('Passwords do not match.');setLoading(true);try{delete values.confirmPassword;const next=await register(values);toast.success('Your CampusFlow account is ready.');navigate(next.role==='admin'?'/admin':'/app')}catch(error){toast.error(errorMessage(error))}finally{setLoading(false)}};if(user)return <Navigate to="/app"/>;return <AuthShell title="Create your student account" copy="A few details, then your campus services are one tap away."><form onSubmit={submit}><Field label="Full name" name="name" required placeholder="Your full name"/><Field label="College email" name="email" type="email" required placeholder="you@college.edu"/><div className="form-grid"><Field label="Student ID" name="studentId" required placeholder="CF2026123"/><Field label="Department" name="department" required placeholder="Computer Science"/></div><Field as="select" label="Year of study" name="yearOfStudy" required defaultValue=""><option value="" disabled>Select year</option>{[1,2,3,4,5,6].map((n)=><option key={n} value={n}>Year {n}</option>)}</Field><div className="form-grid"><Field label="Password" name="password" type="password" minLength="8" required hint="At least 8 characters"/><Field label="Confirm password" name="confirmPassword" type="password" required/></div><Button className="w-full mt-1" loading={loading}>Create account <ArrowRight size={16}/></Button></form><p className="text-sm text-center mt-6">Already registered? <Link className="text-indigo-600 font-bold" to="/login">Sign in</Link></p></AuthShell>}
export function ForgotPassword(){return <AuthShell title="Reset your password" copy="Password reset email delivery is not enabled in this local prototype."><div className="card"><LockKeyhole className="text-indigo-600 mb-3"/><h3>Ask your campus administrator</h3><p>For the hackathon demo, the administrator can verify your identity and reset your account securely.</p><Link className="button button-secondary mt-5" to="/login">Back to sign in</Link></div></AuthShell>}
