import { Link } from 'react-router-dom';
import { ArrowRight, BellRing, CalendarCheck, CheckCircle2, Clock3, MapPin, MousePointerClick, ShieldCheck, Sparkles, Users, Waves, Zap } from 'lucide-react';
import { Button } from '../../components/common/UI';

const featured = [
  { name:'Library Issue & Return', wait:'12 min', people:3, icon:'LIB', tone:'indigo' },
  { name:'Accounts & Fee Office', wait:'8 min', people:2, icon:'ACC', tone:'amber' },
  { name:'Campus Medical Room', wait:'No wait', people:0, icon:'MED', tone:'green' },
  { name:'IT Support Desk', wait:'24 min', people:2, icon:'ITS', tone:'indigo' }
];
export default function Home(){return <>
  <section className="hero"><div className="container hero-grid"><div><span className="eyebrow"><Sparkles size={13}/> Campus services, reimagined</span><h1>Skip the Line.<br/><span className="gradient-text">Get More Done.</span></h1><p className="hero-copy">See live wait times, join a digital queue, or book an appointment—so your day stays yours.</p><div className="hero-actions"><Link className="button button-primary min-h-12 px-6" to="/services">Get a Digital Token <ArrowRight size={17}/></Link><Link className="button button-secondary min-h-12 px-6" to="/how-it-works">See How It Works</Link></div><div className="trust-row"><span><CheckCircle2 size={15} className="text-emerald-500"/> Live queue visibility</span><span><CheckCircle2 size={15} className="text-emerald-500"/> No app download</span><span><CheckCircle2 size={15} className="text-emerald-500"/> Student-friendly</span></div></div>
  <div className="queue-preview" aria-label="Live queue preview"><div className="preview-top"><div><b>Library Issue & Return</b><div className="text-xs text-slate-500 mt-1"><span className="status-dot mr-2"/>Queue is moving</div></div><span className="badge badge-green">Open</span></div><div className="preview-token"><div className="active-token-head"><small>Your digital token</small><BellRing size={19}/></div><div className="token-number">LIB-024</div><p className="text-sm text-indigo-100 mt-0">3 people ahead · About 12 minutes</p><div className="progress"><span style={{width:'64%'}}/></div></div><div className="mini-grid"><div className="mini-stat"><b>LIB-021</b><small>Now serving</small></div><div className="mini-stat"><b>3</b><small>Your position</small></div><div className="mini-stat"><b>Desk 2</b><small>Central Library</small></div></div></div></div></section>
  <section className="section"><div className="container"><div className="section-head"><span className="eyebrow">One clear journey</span><h2>Campus errands without the uncertainty</h2><p>CampusFlow turns an invisible physical line into a simple, trackable experience.</p></div><div className="grid-3"><Step n="01" icon={<MousePointerClick/>} title="Choose a service" text="See which desks are open, how busy they are, and what to bring."/><Step n="02" icon={<Zap/>} title="Join or book" text="Take a digital token now or choose an appointment that fits your schedule."/><Step n="03" icon={<BellRing/>} title="Arrive at the right time" text="Follow your position and get a clear notification when the desk is ready."/></div></div></section>
  <section className="section alt"><div className="container"><div className="section-head"><span className="eyebrow">Live campus</span><h2>Know before you go</h2><p>Queue information that helps you choose the right moment—not just the shortest line.</p></div><div className="grid-4">{featured.map((item)=><div className="card service-card" key={item.name}><div className="service-head"><span className="icon-tile !mb-0 font-bold text-xs">{item.icon}</span><span className={`badge badge-${item.tone}`}>Open</span></div><div><h3>{item.name}</h3><p className="mt-1">Campus services</p></div><div className="service-meta"><span><Users size={14} className="inline mr-1"/>{item.people} waiting</span><b className="text-slate-700"><Clock3 size={14} className="inline mr-1"/>{item.wait}</b></div></div>)}</div><div className="text-center mt-8"><Link to="/services" className="button button-secondary">Explore all services <ArrowRight size={16}/></Link></div></div></section>
  <section className="section"><div className="container"><div className="grid-3"><Benefit icon={<Clock3/>} title="Time back for students" text="Study, meet friends, or get lunch while your place in line stays visible."/><Benefit icon={<CalendarCheck/>} title="Fewer crowded corridors" text="Appointments and digital queues spread demand across the day."/><Benefit icon={<ShieldCheck/>} title="Clearer operations" text="Campus teams can manage flow, spot peak hours, and serve students fairly."/></div></div></section>
  <section className="section alt"><div className="container"><div className="section-head"><span className="eyebrow">Built around real days</span><h2>Less waiting. More certainty.</h2></div><div className="grid-3"><Quote text="I checked the accounts queue between lectures and joined when it dropped. No missed class, no guessing." name="Riya Sharma" role="Second-year student"/><Quote text="The desk view makes the next action obvious. Our staff spends less time managing the line itself." name="Vikram Nair" role="Student services coordinator"/><Quote text="Booking a resume review ahead of placement week was much calmer than waiting outside the cell." name="Aditya Sen" role="Final-year student"/></div></div></section>
  <section className="section"><div className="container"><div className="cta-band"><div><h2>Your campus day should flow.</h2><p>Find a service, check the queue, and keep moving.</p></div><Link className="button button-secondary min-h-12" to="/register">Create your account <ArrowRight size={17}/></Link></div></div></section>
  </>}
function Step({n,icon,title,text}){return <div className="card"><div className="step-number">STEP {n}</div><span className="icon-tile">{icon}</span><h3>{title}</h3><p>{text}</p></div>};
function Benefit({icon,title,text}){return <div className="card"><span className="icon-tile">{icon}</span><h3>{title}</h3><p>{text}</p></div>};
function Quote({text,name,role}){return <blockquote className="card"><p className="!text-slate-700">“{text}”</p><footer className="mt-5"><b className="text-sm">{name}</b><small className="block text-slate-500 mt-1">{role}</small></footer></blockquote>}
