import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { CalendarDays, Clock3, MapPin, Search, Users } from 'lucide-react';
import api from '../../services/api';
import { Badge, EmptyState, Spinner } from '../../components/common/UI';

export default function Services(){
  const [services,setServices]=useState([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [category,setCategory]=useState('All'); const [availability,setAvailability]=useState('all');
  useEffect(()=>{api.get('/services').then(({data})=>setServices(data.services)).catch(()=>setServices([])).finally(()=>setLoading(false))},[]);
  const categories=['All',...new Set(services.map((s)=>s.category))];
  const filtered=useMemo(()=>services.filter((s)=>(category==='All'||s.category===category)&&(availability==='all'||(availability==='open'?s.queueOpen:!s.queueOpen))&&`${s.name} ${s.description}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.estimatedWait-b.estimatedWait),[services,category,availability,search]);
  return <><section className="page-hero"><span className="eyebrow">Live service directory</span><h1>Where can we help?</h1><p>Compare queues, find the right desk, and choose between a digital token or a scheduled appointment.</p></section><section className="section pt-10"><div className="container"><div className="toolbar"><div className="search-box"><Search size={19}/><input aria-label="Search services" placeholder="Search services, locations, departments…" value={search} onChange={(e)=>setSearch(e.target.value)}/></div><select aria-label="Filter category" value={category} onChange={(e)=>setCategory(e.target.value)}>{categories.map((c)=><option key={c}>{c}</option>)}</select><select aria-label="Filter availability" value={availability} onChange={(e)=>setAvailability(e.target.value)}><option value="all">Any availability</option><option value="open">Open queues</option><option value="closed">Closed queues</option></select></div>{loading?<Spinner/>:filtered.length?<div className="grid-3">{filtered.map((service)=><ServiceCard service={service} key={service._id}/>)}</div>:<EmptyState title="No services match those filters" text="Try a broader search or clear an availability filter."/>}</div></section></>;
}
export function ServiceCard({service,compact=false}){const open=service.queueOpen&&service.status!=='closed';return <article className="card service-card"><div className="service-head"><span className="icon-tile !mb-0 font-bold text-xs">{service.code}</span><Badge tone={open?'green':'red'}>{open?'Queue open':'Queue closed'}</Badge></div><div><span className="text-xs text-indigo-600 font-bold uppercase tracking-wide">{service.category}</span><h3 className="mt-2">{service.name}</h3>{!compact&&<p>{service.description}</p>}</div><div className="service-meta"><span><Users size={14} className="inline mr-1"/>{service.waitingCount||0} waiting</span><b><Clock3 size={14} className="inline mr-1"/>{service.estimatedWait||0} min</b></div>{!compact&&<div className="text-xs text-slate-500"><MapPin size={14} className="inline mr-1"/>{service.location}</div>}<div className="service-actions"><Link className={`button ${open?'button-primary':'button-secondary'}`} to={`/app/services/${service._id}`}>{open?'View & join':'View details'}</Link><Link className="button button-secondary" to={`/app/services/${service._id}?book=1`}><CalendarDays size={15}/> Book</Link></div></article>}
